# Generated by Django 3.1.3 on 2020-12-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
