# Generated by Django 3.1.3 on 2020-12-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='dateOFpost',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
