# Generated by Django 3.1.3 on 2020-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20201206_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/Post'),
        ),
    ]
