# Generated by Django 3.1.3 on 2020-12-06 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0007_viewed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewed',
            new_name='View',
        ),
    ]
