# Generated by Django 3.1.3 on 2020-12-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20201206_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='user_image/default/default.jpg', upload_to='user_image/Profiles'),
        ),
    ]
