# Generated by Django 3.1.3 on 2020-12-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='followed',
        ),
    ]
