# Generated by Django 3.1.3 on 2020-12-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_following_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='views',
        ),
    ]
