# Generated by Django 3.1.3 on 2020-12-15 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0014_remove_view_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='Total_View',
        ),
    ]
