# Generated by Django 3.1.3 on 2020-12-15 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0015_auto_20201215_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Total_View',
            new_name='View',
        ),
    ]
