# Generated by Django 3.1.3 on 2020-12-18 06:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0016_auto_20201215_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='T_View',
        ),
    ]
